workflows:
  default-workflow:
    name: Mainalasri Technician Pro
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      node: 18
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch:
        - main
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android
        script: |
          eas build --platform android --non-interactive
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
    publishing:
      email:
        recipients:
          - m3een120131937@gmail.com
        notify:
          on_success: true
          on_failure: true