workflows:
  default-workflow:
    name: Mainalasri Technician Pro
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      node: 18.0.0
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g eas-cli expo-cli
      - name: Login to Expo
        script: |
          echo "EXPO_TOKEN=$EXPO_TOKEN" >> ~/.bashrc
          source ~/.bashrc
          eas build --platform android --non-interactive
    artifacts:
      - build/**/*.apk