const colors = {
  light: {
    text: "#0a0e1a",
    tint: "#00d4ff",
    background: "#f0f4f8",
    foreground: "#0a0e1a",
    card: "#ffffff",
    cardForeground: "#0a0e1a",
    primary: "#0066ff",
    primaryForeground: "#ffffff",
    secondary: "#e8edf5",
    secondaryForeground: "#1a2540",
    muted: "#e8edf5",
    mutedForeground: "#6b7a99",
    accent: "#00d4ff",
    accentForeground: "#0a0e1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#d1dae8",
    input: "#d1dae8",
  },
  dark: {
    text: "#e8edf5",
    tint: "#00d4ff",
    background: "#080c18",
    foreground: "#e8edf5",
    card: "#0f1629",
    cardForeground: "#e8edf5",
    primary: "#00d4ff",
    primaryForeground: "#080c18",
    secondary: "#1a2540",
    secondaryForeground: "#e8edf5",
    muted: "#141d35",
    mutedForeground: "#6b7a99",
    accent: "#0066ff",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e2d4d",
    input: "#1e2d4d",
  },
  radius: 16,
};

export default colors;
